### PR TITLE
STUD-497: Deletes appledouble files prior to ingesting

### PR DESCRIPTION
**Pull request by leafknode**
@dlamy

Added code to delete apple double files.

### CODE REVIEW

**Comment by leafknode** [comment]
Actually, I submitted this too soon.  Please do not accept this PR (I would close the PR myself but I don't have permission)

**Comment by dlamy** [comment]
So you've tested this and no issues with deleting these files before we move them?

**Comment by dlamy** [comment]
Just noticed your comment.  I've fixed the permissions so you should be good.

**Comment by leafknode** [comment]
I tested and it seemed to work but now I'm seeing issues.  I'm not sure they are related so I'm re-testing

**Comment by leafknode** [comment]
cool, ty.  I've verified that the bug I'm seeing is not related to this AppleDouble deletion code.  Have performed multiple tests on this with both single and multiple file sets and it looks good.

Please merge the PR when you're ready.

**Comment by leafknode** [comment]
Once this PR goes in, we can release it and update RE 9.3 and 9.2 appropriately.

**Comment by leafknode** [comment]
@jfairley 
Once this gets accepted, I'd like to release it.  I'd like to solicit your help with this release since I haven't done it here yet.

**Pull request merged**
